export const PRACTICE_TYPES = [
  'General',
  'Pediatric',
  'Cosmetic',
  'Implant',
  'Orthodontic',
  'Endodontic',
  'Other',
];

export const TARGET_AUDIENCES = [
  { id: 'families', label: 'Families' },
  { id: 'kids', label: 'Kids' },
  { id: 'adults', label: 'Adults' },
  { id: 'seniors', label: 'Seniors' },
  { id: 'professionals', label: 'Professionals' },
  { id: 'high-end', label: 'High-End Clients' },
];

export const BRAND_PERSONALITIES = [
  { id: 'friendly', label: 'Friendly' },
  { id: 'professional', label: 'Professional' },
  { id: 'luxury', label: 'Luxury' },
  { id: 'modern-tech', label: 'Modern/Tech' },
  { id: 'warm', label: 'Warm' },
  { id: 'playful', label: 'Playful' },
];

export const DOMAIN_EXTENSIONS = ['.com', '.clinic', '.dentist'];

export const COUNTRIES = [
    { value: 'afghanistan', label: 'Afghanistan', tld: '.af' },
    { value: 'aland-islands', label: 'Åland Islands', tld: '.ax' },
    { value: 'albania', label: 'Albania', tld: '.al' },
    { value: 'algeria', label: 'Algeria', tld: '.dz' },
    { value: 'american-samoa', label: 'American Samoa', tld: '.as' },
    { value: 'andorra', label: 'Andorra', tld: '.ad' },
    { value: 'angola', label: 'Angola', tld: '.ao' },
    { value: 'anguilla', label: 'Anguilla', tld: '.ai' },
    { value: 'antarctica', label: 'Antarctica', tld: '.aq' },
    { value: 'antigua-and-barbuda', label: 'Antigua and Barbuda', tld: '.ag' },
    { value: 'argentina', label: 'Argentina', tld: '.ar' },
    { value: 'armenia', label: 'Armenia', tld: '.am' },
    { value: 'aruba', label: 'Aruba', tld: '.aw' },
    { value: 'australia', label: 'Australia', tld: '.com.au' },
    { value: 'austria', label: 'Austria', tld: '.at' },
    { value: 'azerbaijan', label: 'Azerbaijan', tld: '.az' },
    { value: 'bahamas', label: 'Bahamas', tld: '.bs' },
    { value: 'bahrain', label: 'Bahrain', tld: '.bh' },
    { value: 'bangladesh', label: 'Bangladesh', tld: '.bd' },
    { value: 'barbados', label: 'Barbados', tld: '.bb' },
    { value: 'belarus', label: 'Belarus', tld: '.by' },
    { value: 'belgium', label: 'Belgium', tld: '.be' },
    { value: 'belize', label: 'Belize', tld: '.bz' },
    { value: 'benin', label: 'Benin', tld: '.bj' },
    { value: 'bermuda', label: 'Bermuda', tld: '.bm' },
    { value: 'bhutan', label: 'Bhutan', tld: '.bt' },
    { value: 'bolivia', label: 'Bolivia', tld: '.bo' },
    { value: 'bonaire-sint-eustatius-and-saba', label: 'Bonaire, Sint Eustatius and Saba', tld: '.bq' },
    { value: 'bosnia-and-herzegovina', label: 'Bosnia and Herzegovina', tld: '.ba' },
    { value: 'botswana', label: 'Botswana', tld: '.bw' },
    { value: 'bouvet-island', label: 'Bouvet Island', tld: '.bv' },
    { value: 'brazil', label: 'Brazil', tld: '.br' },
    { value: 'british-indian-ocean-territory', label: 'British Indian Ocean Territory', tld: '.io' },
    { value: 'brunei-darussalam', label: 'Brunei Darussalam', tld: '.bn' },
    { value: 'bulgaria', label: 'Bulgaria', tld: '.bg' },
    { value: 'burkina-faso', label: 'Burkina Faso', tld: '.bf' },
    { value: 'burundi', label: 'Burundi', tld: '.bi' },
    { value: 'cambodia', label: 'Cambodia', tld: '.kh' },
    { value: 'cameroon', label: 'Cameroon', tld: '.cm' },
    { value: 'canada', label: 'Canada', tld: '.ca' },
    { value: 'cape-verde', label: 'Cape Verde', tld: '.cv' },
    { value: 'cayman-islands', label: 'Cayman Islands', tld: '.ky' },
    { value: 'central-african-republic', label: 'Central African Republic', tld: '.cf' },
    { value: 'chad', label: 'Chad', tld: '.td' },
    { value: 'chile', label: 'Chile', tld: '.cl' },
    { value: 'china', label: 'China', tld: '.cn' },
    { value: 'christmas-island', label: 'Christmas Island', tld: '.cx' },
    { value: 'cocos-keeling-islands', label: 'Cocos (Keeling) Islands', tld: '.cc' },
    { value: 'colombia', label: 'Colombia', tld: '.co' },
    { value: 'comoros', label: 'Comoros', tld: '.km' },
    { value: 'congo', label: 'Congo', tld: '.cg' },
    { value: 'congo-democratic-republic-of-the', label: 'Congo, Democratic Republic of the', tld: '.cd' },
    { value: 'cook-islands', label: 'Cook Islands', tld: '.ck' },
    { value: 'costa-rica', label: 'Costa Rica', tld: '.cr' },
    { value: 'cote-divoire', label: 'Côte d\'Ivoire', tld: '.ci' },
    { value: 'croatia', label: 'Croatia', tld: '.hr' },
    { value: 'cuba', label: 'Cuba', tld: '.cu' },
    { value: 'curacao', label: 'Curaçao', tld: '.cw' },
    { value: 'cyprus', label: 'Cyprus', tld: '.cy' },
    { value: 'czech-republic', label: 'Czech Republic', tld: '.cz' },
    { value: 'denmark', label: 'Denmark', tld: '.dk' },
    { value: 'djibouti', label: 'Djibouti', tld: '.dj' },
    { value: 'dominica', label: 'Dominica', tld: '.dm' },
    { value: 'dominican-republic', label: 'Dominican Republic', tld: '.do' },
    { value: 'ecuador', label: 'Ecuador', tld: '.ec' },
    { value: 'egypt', label: 'Egypt', tld: '.eg' },
    { value: 'el-salvador', label: 'El Salvador', tld: '.sv' },
    { value: 'equatorial-guinea', label: 'Equatorial Guinea', tld: '.gq' },
    { value: 'eritrea', label: 'Eritrea', tld: '.er' },
    { value: 'estonia', label: 'Estonia', tld: '.ee' },
    { value: 'ethiopia', label: 'Ethiopia', tld: '.et' },
    { value: 'falkland-islands-malvinas', label: 'Falkland Islands (Malvinas)', tld: '.fk' },
    { value: 'faroe-islands', label: 'Faroe Islands', tld: '.fo' },
    { value: 'fiji', label: 'Fiji', tld: '.fj' },
    { value: 'finland', label: 'Finland', tld: '.fi' },
    { value: 'france', label: 'France', tld: '.fr' },
    { value: 'french-guiana', label: 'French Guiana', tld: '.gf' },
    { value: 'french-polynesia', label: 'French Polynesia', tld: '.pf' },
    { value: 'french-southern-territories', label: 'French Southern Territories', tld: '.tf' },
    { value: 'gabon', label: 'Gabon', tld: '.ga' },
    { value: 'gambia', label: 'Gambia', tld: '.gm' },
    { value: 'georgia', label: 'Georgia', tld: '.ge' },
    { value: 'germany', label: 'Germany', tld: '.de' },
    { value: 'ghana', label: 'Ghana', tld: '.gh' },
    { value: 'gibraltar', label: 'Gibraltar', tld: '.gi' },
    { value: 'greece', label: 'Greece', tld: '.gr' },
    { value: 'greenland', label: 'Greenland', tld: '.gl' },
    { value: 'grenada', label: 'Grenada', tld: '.gd' },
    { value: 'guadeloupe', label: 'Guadeloupe', tld: '.gp' },
    { value: 'guam', label: 'Guam', tld: '.gu' },
    { value: 'guatemala', label: 'Guatemala', tld: '.gt' },
    { value: 'guernsey', label: 'Guernsey', tld: '.gg' },
    { value: 'guinea', label: 'Guinea', tld: '.gn' },
    { value: 'guinea-bissau', label: 'Guinea-Bissau', tld: '.gw' },
    { value: 'guyana', label: 'Guyana', tld: '.gy' },
    { value: 'haiti', label: 'Haiti', tld: '.ht' },
    { value: 'heard-island-and-mcdonald-islands', label: 'Heard Island and McDonald Islands', tld: '.hm' },
    { value: 'holy-see-vatican-city-state', label: 'Holy See (Vatican City State)', tld: '.va' },
    { value: 'honduras', label: 'Honduras', tld: '.hn' },
    { value: 'hong-kong', label: 'Hong Kong', tld: '.hk' },
    { value: 'hungary', label: 'Hungary', tld: '.hu' },
    { value: 'iceland', label: 'Iceland', tld: '.is' },
    { value: 'india', label: 'India', tld: '.in' },
    { value: 'indonesia', label: 'Indonesia', tld: '.id' },
    { value: 'iran-islamic-republic-of', label: 'Iran, Islamic Republic of', tld: '.ir' },
    { value: 'iraq', label: 'Iraq', tld: '.iq' },
    { value: 'ireland', label: 'Ireland', tld: '.ie' },
    { value: 'isle-of-man', label: 'Isle of Man', tld: '.im' },
    { value: 'israel', label: 'Israel', tld: '.il' },
    { value: 'italy', label: 'Italy', tld: '.it' },
    { value: 'jamaica', label: 'Jamaica', tld: '.jm' },
    { value: 'japan', label: 'Japan', tld: '.jp' },
    { value: 'jersey', label: 'Jersey', tld: '.je' },
    { value: 'jordan', label: 'Jordan', tld: '.jo' },
    { value: 'kazakhstan', label: 'Kazakhstan', tld: '.kz' },
    { value: 'kenya', label: 'Kenya', tld: '.ke' },
    { value: 'kiribati', label: 'Kiribati', tld: '.ki' },
    { value: 'korea-democratic-peoples-republic-of', label: 'Korea, Democratic People\'s Republic of', tld: '.kp' },
    { value: 'korea-republic-of', label: 'Korea, Republic of', tld: '.kr' },
    { value: 'kuwait', label: 'Kuwait', tld: '.kw' },
    { value: 'kyrgyzstan', label: 'Kyrgyzstan', tld: '.kg' },
    { value: 'lao-peoples-democratic-republic', label: 'Lao People\'s Democratic Republic', tld: '.la' },
    { value: 'latvia', label: 'Latvia', tld: '.lv' },
    { value: 'lebanon', label: 'Lebanon', tld: '.lb' },
    { value: 'lesotho', label: 'Lesotho', tld: '.ls' },
    { value: 'liberia', label: 'Liberia', tld: '.lr' },
    { value: 'libya', label: 'Libya', tld: '.ly' },
    { value: 'liechtenstein', label: 'Liechtenstein', tld: '.li' },
    { value: 'lithuania', label: 'Lithuania', tld: '.lt' },
    { value: 'luxembourg', label: 'Luxembourg', tld: '.lu' },
    { value: 'macao', label: 'Macao', tld: '.mo' },
    { value: 'macedonia-the-former-yugoslav-republic-of', label: 'Macedonia, the former Yugoslav Republic of', tld: '.mk' },
    { value: 'madagascar', label: 'Madagascar', tld: '.mg' },
    { value: 'malawi', label: 'Malawi', tld: '.mw' },
    { value: 'malaysia', label: 'Malaysia', tld: '.my' },
    { value: 'maldives', label: 'Maldives', tld: '.mv' },
    { value: 'mali', label: 'Mali', tld: '.ml' },
    { value: 'malta', label: 'Malta', tld: '.mt' },
    { value: 'marshall-islands', label: 'Marshall Islands', tld: '.mh' },
    { value: 'martinique', label: 'Martinique', tld: '.mq' },
    { value: 'mauritania', label: 'Mauritania', tld: '.mr' },
    { value: 'mauritius', label: 'Mauritius', tld: '.mu' },
    { value: 'mayotte', label: 'Mayotte', tld: '.yt' },
    { value: 'mexico', label: 'Mexico', tld: '.mx' },
    { value: 'micronesia-federated-states-of', label: 'Micronesia, Federated States of', tld: '.fm' },
    { value: 'moldova-republic-of', label: 'Moldova, Republic of', tld: '.md' },
    { value: 'monaco', label: 'Monaco', tld: '.mc' },
    { value: 'mongolia', label: 'Mongolia', tld: '.mn' },
    { value: 'montenegro', label: 'Montenegro', tld: '.me' },
    { value: 'montserrat', label: 'Montserrat', tld: '.ms' },
    { value: 'morocco', label: 'Morocco', tld: '.ma' },
    { value: 'mozambique', label: 'Mozambique', tld: '.mz' },
    { value: 'myanmar', label: 'Myanmar', tld: '.mm' },
    { value: 'namibia', label: 'Namibia', tld: '.na' },
    { value: 'nauru', label: 'Nauru', tld: '.nr' },
    { value: 'nepal', label: 'Nepal', tld: '.np' },
    { value: 'netherlands', label: 'Netherlands', tld: '.nl' },
    { value: 'new-caledonia', label: 'New Caledonia', tld: '.nc' },
    { value: 'new-zealand', label: 'New Zealand', tld: '.co.nz' },
    { value: 'nicaragua', label: 'Nicaragua', tld: '.ni' },
    { value: 'niger', label: 'Niger', tld: '.ne' },
    { value: 'nigeria', label: 'Nigeria', tld: '.ng' },
    { value: 'niue', label: 'Niue', tld: '.nu' },
    { value: 'norfolk-island', label: 'Norfolk Island', tld: '.nf' },
    { value: 'northern-mariana-islands', label: 'Northern Mariana Islands', tld: '.mp' },
    { value: 'norway', label: 'Norway', tld: '.no' },
    { value: 'oman', label: 'Oman', tld: '.om' },
    { value: 'pakistan', label: 'Pakistan', tld: '.pk' },
    { value: 'palau', label: 'Palau', tld: '.pw' },
    { value: 'palestine-state-of', label: 'Palestine, State of', tld: '.ps' },
    { value: 'panama', label: 'Panama', tld: '.pa' },
    { value: 'papua-new-guinea', label: 'Papua New Guinea', tld: '.pg' },
    { value: 'paraguay', label: 'Paraguay', tld: '.py' },
    { value: 'peru', label: 'Peru', tld: '.pe' },
    { value: 'philippines', label: 'Philippines', tld: '.ph' },
    { value: 'pitcairn', label: 'Pitcairn', tld: '.pn' },
    { value: 'poland', label: 'Poland', tld: '.pl' },
    { value: 'portugal', label: 'Portugal', tld: '.pt' },
    { value: 'puerto-rico', label: 'Puerto Rico', tld: '.pr' },
    { value: 'qatar', label: 'Qatar', tld: '.qa' },
    { value: 'reunion', label: 'Réunion', tld: '.re' },
    { value: 'romania', label: 'Romania', tld: '.ro' },
    { value: 'russian-federation', label: 'Russian Federation', tld: '.ru' },
    { value: 'rwanda', label: 'Rwanda', tld: '.rw' },
    { value: 'saint-barthelemy', label: 'Saint Barthélemy', tld: '.bl' },
    { value: 'saint-helena-ascension-and-tristan-da-cunha', label: 'Saint Helena, Ascension and Tristan da Cunha', tld: '.sh' },
    { value: 'saint-kitts-and-nevis', label: 'Saint Kitts and Nevis', tld: '.kn' },
    { value: 'saint-lucia', label: 'Saint Lucia', tld: '.lc' },
    { value: 'saint-martin-french-part', label: 'Saint Martin (French part)', tld: '.mf' },
    { value: 'saint-pierre-and-miquelon', label: 'Saint Pierre and Miquelon', tld: '.pm' },
    { value: 'saint-vincent-and-the-grenadines', label: 'Saint Vincent and the Grenadines', tld: '.vc' },
    { value: 'samoa', label: 'Samoa', tld: '.ws' },
    { value: 'san-marino', label: 'San Marino', tld: '.sm' },
    { value: 'sao-tome-and-principe', label: 'Sao Tome and Principe', tld: '.st' },
    { value: 'saudi-arabia', label: 'Saudi Arabia', tld: '.sa' },
    { value: 'senegal', label: 'Senegal', tld: '.sn' },
    { value: 'serbia', label: 'Serbia', tld: '.rs' },
    { value: 'seychelles', label: 'Seychelles', tld: '.sc' },
    { value: 'sierra-leone', label: 'Sierra Leone', tld: '.sl' },
    { value: 'singapore', label: 'Singapore', tld: '.sg' },
    { value: 'sint-maarten-dutch-part', label: 'Sint Maarten (Dutch part)', tld: '.sx' },
    { value: 'slovakia', label: 'Slovakia', tld: '.sk' },
    { value: 'slovenia', label: 'Slovenia', tld: '.si' },
    { value: 'solomon-islands', label: 'Solomon Islands', tld: '.sb' },
    { value: 'somalia', label: 'Somalia', tld: '.so' },
    { value: 'south-africa', label: 'South Africa', tld: '.za' },
    { value: 'south-georgia-and-the-south-sandwich-islands', label: 'South Georgia and the South Sandwich Islands', tld: '.gs' },
    { value: 'south-sudan', label: 'South Sudan', tld: '.ss' },
    { value: 'spain', label: 'Spain', tld: '.es' },
    { value: 'sri-lanka', label: 'Sri Lanka', tld: '.lk' },
    { value: 'sudan', label: 'Sudan', tld: '.sd' },
    { value: 'suriname', label: 'Suriname', tld: '.sr' },
    { value: 'svalbard-and-jan-mayen', label: 'Svalbard and Jan Mayen', tld: '.sj' },
    { value: 'swaziland', label: 'Swaziland', tld: '.sz' },
    { value: 'sweden', label: 'Sweden', tld: '.se' },
    { value: 'switzerland', label: 'Switzerland', tld: '.ch' },
    { value: 'syrian-arab-republic', label: 'Syrian Arab Republic', tld: '.sy' },
    { value: 'taiwan-province-of-china', label: 'Taiwan, Province of China', tld: '.tw' },
    { value: 'tajikistan', label: 'Tajikistan', tld: '.tj' },
    { value: 'tanzania-united-republic-of', label: 'Tanzania, United Republic of', tld: '.tz' },
    { value: 'thailand', label: 'Thailand', tld: '.th' },
    { value: 'timor-leste', label: 'Timor-Leste', tld: '.tl' },
    { value: 'togo', label: 'Togo', tld: '.tg' },
    { value: 'tokelau', label: 'Tokelau', tld: '.tk' },
    { value: 'tonga', label: 'Tonga', tld: '.to' },
    { value: 'trinidad-and-tobago', label: 'Trinidad and Tobago', tld: '.tt' },
    { value: 'tunisia', label: 'Tunisia', tld: '.tn' },
    { value: 'turkey', label: 'Turkey', tld: '.tr' },
    { value: 'turkmenistan', label: 'Turkmenistan', tld: '.tm' },
    { value: 'turks-and-caicos-islands', label: 'Turks and Caicos Islands', tld: '.tc' },
    { value: 'tuvalu', label: 'Tuvalu', tld: '.tv' },
    { value: 'uganda', label: 'Uganda', tld: '.ug' },
    { value: 'ukraine', label: 'Ukraine', tld: '.ua' },
    { value: 'united-arab-emirates', label: 'United Arab Emirates', tld: '.ae' },
    { value: 'uk', label: 'United Kingdom', tld: '.co.uk' },
    { value: 'usa', label: 'United States', tld: '.us' },
    { value: 'united-states-minor-outlying-islands', label: 'United States Minor Outlying Islands', tld: '.um' },
    { value: 'uruguay', label: 'Uruguay', tld: '.uy' },
    { value: 'uzbekistan', label: 'Uzbekistan', tld: '.uz' },
    { value: 'vanuatu', label: 'Vanuatu', tld: '.vu' },
    { value: 'venezuela-bolivarian-republic-of', label: 'Venezuela, Bolivarian Republic of', tld: '.ve' },
    { value: 'viet-nam', label: 'Viet Nam', tld: '.vn' },
    { value: 'virgin-islands-british', label: 'Virgin Islands, British', tld: '.vg' },
    { value: 'virgin-islands-us', label: 'Virgin Islands, U.S.', tld: '.vi' },
    { value: 'wallis-and-futuna', label: 'Wallis and Futuna', tld: '.wf' },
    { value: 'western-sahara', label: 'Western Sahara', tld: '.eh' },
    { value: 'yemen', label: 'Yemen', tld: '.ye' },
    { value: 'zambia', label: 'Zambia', tld: '.zm' },
    { value: 'zimbabwe', label: 'Zimbabwe', tld: '.zw' },
];
